import type { Metadata, Viewport } from 'next';
import './styles/bootstrap.min.css';
import './styles/font-marcellus.css';
import './styles/main.css';
import Navigation from '../components/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main id="main-content">{children}</main>
      </body>
    </html>
  );
}
