name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DJANGO_SETTINGS_MODULE: bakerydemo.settings.dev
  NEXT_PUBLIC_WAGTAIL_API_HOST: http://localhost:8000

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
      - run: biome ci
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm run test

  render:
    needs: check
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - run: git clone --depth 1 --branch headless https://github.com/wagtail/bakerydemo.git bakerydemo
      - run: uv venv
        working-directory: bakerydemo
      - run: uv pip install -r requirements/base.txt
        working-directory: bakerydemo
      - run: |
          uv run manage.py migrate --noinput
          uv run manage.py load_initial_data
        working-directory: bakerydemo
      - run: |
          uv run manage.py runserver 0.0.0.0:8000 &
          sleep 3
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:8000/api/v2/pages/
        working-directory: bakerydemo

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_WAGTAIL_API_HOST: http://localhost:8000
